In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
# merging the two dataframes based on their title
# could have done it with id as well, but it's name is different in both, so we'll just choose title

movies = movies.merge(credits, on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Columns we're going to take into recommendation:

- Genres
- id
- keyword
- title
- overview
- cast
- crew

In [7]:
movies = movies[['genres', 'id', 'keywords', 'title', 'overview', 'cast', 'crew']]

In [8]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
from ast import literal_eval

def convert(obj):
    lst = []
    for i in literal_eval(obj):
        lst.append(i['name'])
    
    return lst

In [14]:
movies['genres'] = movies['genres'].apply(convert)

In [15]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies['keywords'] = movies['keywords'].apply(convert)

In [17]:
def convert3(obj):
    lst = []
    counter = 0
    
    for i in literal_eval(obj):
        if counter != 3:
            lst.append(i['name'])
            counter += 1
        else: break
    
    return lst

In [18]:
movies['cast'] = movies['cast'].apply(convert3)

In [19]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def fetch_director(obj):
    lst = []
    for i in literal_eval(obj):
        if i['job'] == 'Director':
            lst.append(i['name'])
            break
    return lst

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [22]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [23]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [24]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [25]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [26]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['crew']

In [27]:
movies.head()

,genres,id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [28]:
new_df = movies[['id', 'title', 'tags']]
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [29]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

/tmp/ipykernel_14735/1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [30]:
new_df.iloc[0].tags

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d JamesCameron'

In [31]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

/tmp/ipykernel_14735/1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [32]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [36]:
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
ps = PorterStemmer()
cv = CountVectorizer(max_features=5000, stop_words='english')

In [40]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [42]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_14735/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [49]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [52]:
cv.vocabulary_

{'century': 748,
 'marin': 2758,
 'dispatch': 1283,
 'moon': 2952,
 'pandora': 3232,
 'uniqu': 4686,
 'mission': 2917,
 'becom': 451,
 'torn': 4547,
 'follow': 1734,
 'order': 3183,
 'protect': 3505,
 'alien': 169,
 'action': 87,
 'adventur': 116,
 'fantasi': 1625,
 'sciencefict': 3895,
 'cultureclash': 1089,
 'futur': 1817,
 'societi': 4125,
 'spacetravel': 4179,
 'futurist': 1819,
 'romanc': 3789,
 'space': 4173,
 'tribe': 4601,
 'alienplanet': 172,
 'soldier': 4133,
 'battl': 434,
 '3d': 53,
 'jamescameron': 2358,
 'captain': 696,
 'long': 2643,
 'believ': 467,
 'dead': 1147,
 'ha': 1977,
 'come': 906,
 'life': 2591,
 'head': 2030,
 'edg': 1412,
 'earth': 1401,
 'turner': 4628,
 'elizabeth': 1437,
 'noth': 3112,
 'quit': 3547,
 'ocean': 3142,
 'drugabus': 1361,
 'exoticisland': 1561,
 'loveofone': 2680,
 'slif': 4098,
 'traitor': 4579,
 'shipwreck': 4021,
 'ship': 4020,
 'allianc': 179,
 'afterlif': 131,
 'fighter': 1677,
 'pirat': 3346,
 'aftercreditssting': 130,
 'goreverbinski': 1902,
 'messag': 2852,
 'bond': 557,
 'past': 3265,
 'send': 3955,
 'trail': 4575,
 'uncov': 4658,
 'sinist': 4065,
 'organization': 3187,
 'polit': 3389,
 'forc': 1742,
 'secret': 3925,
 'servic': 3976,
 'alive': 176,
 'deceit': 1164,
 'reveal': 3717,
 'terribl': 4463,
 'truth': 4619,
 'crime': 1060,
 'spi': 4195,
 'basedonnovel': 421,
 'secretag': 3926,
 'sequel': 3965,
 'mi6': 2862,
 'britishsecretservic': 611,
 'sammend': 3857,
 'death': 1155,
 'district': 1289,
 'attorney': 347,
 'harvey': 2019,
 'dent': 1193,
 'batman': 433,
 'assum': 330,
 'respons': 3699,
 'late': 2538,
 'reput': 3684,
 'subsequ': 4318,
 'hunt': 2168,
 'gotham': 1907,
 'citi': 835,
 'polic': 3379,
 'department': 1196,
 'year': 4975,
 'later': 2539,
 'encount': 1464,
 'mysteri': 3012,
 'kyle': 2510,
 'villain': 4786,
 'new': 3069,
 'terrorist': 4469,
 'leader': 2554,
 'overwhelm': 3208,
 'dark': 1125,
 'knight': 2495,
 'resurfac': 3707,
 'brand': 582,
 'enemy': 1472,
 'drama': 1339,
 'thriller': 4502,
 'dccomic': 1145,
 'crimefight': 1061,
 'secretident': 3929,
 'burglar': 651,
 'gothamc': 1908,
 'vigilant': 4782,
 'cover': 1034,
 'superhero': 4349,
 'terror': 4468,
 'destruct': 1222,
 'imax': 2210,
 'flood': 1720,
 'christophernolan': 822,
 'john': 2407,
 'carter': 718,
 'war': 4837,
 'militari': 2888,
 'inexplic': 2247,
 'transport': 4584,
 'exot': 1560,
 'planet': 3355,
 'reluctantli': 3663,
 'embroil': 1450,
 'epic': 1499,
 'conflict': 956,
 'world': 4946,
 'brink': 608,
 'collapse': 887,
 'rediscov': 3630,
 'hi': 2062,
 'human': 2158,
 'realiz': 3602,
 'surviv': 4376,
 'peopl': 3291,
 'rest': 3701,
 'hands': 1989,
 'mar': 2750,
 'medallion': 2824,
 'princess': 3464,
 'steampunk': 4244,
 'martian': 2775,
 'escap': 1509,
 'superhumanstrength': 4351,
 '19thcenturi': 41,
 'seemingli': 3945,
 'spider': 4196,
 'man': 2734,
 'goe': 1893,
 'includ': 2229,
 'shape': 4003,
 'shift': 4018,
 'superpow': 4356,
 'alter': 185,
 'ego': 1421,
 'peter': 3308,
 'parker': 3250,
 'deal': 1152,
 'nemesi': 3059,
 'eddi': 1411,
 'caught': 733,
 'love': 2676,
 'triangle': 4600,
 'dualident': 1372,
 'amnesia': 207,
 'forgiv': 1752,
 'wretch': 4961,
 'deathofafriend': 1156,
 'sand': 3862,
 'hostil': 2140,
 'marvelcom': 2780,
 'reveng': 3720,
 'samraimi': 3858,
 'kingdom': 2487,
 'bandit': 397,
 'flynn': 1726,
 'rider': 3738,
 'hide': 2065,
 'tower': 4559,
 'taken': 4409,
 'hostag': 2138,
 'beauti': 444,
 'bound': 567,
 'teen': 4436,
 '70': 58,
 'feet': 1655,
 'golden': 1895,
 'hair': 1980,
 'curiou': 1094,
 'look': 2646,
 'ticket': 4512,
 'lock': 2634,
 'away': 372,
 'years': 4977,
 'strike': 4291,
 'handsom': 1990,
 'thief': 4488,
 'unlik': 4695,
 'duo': 1382,
 'set': 3979,
 'pack': 3214,
 'complet': 934,
 'super': 4347,
 'cop': 1001,
 'gang': 1833,
 'pub': 3518,
 'anim': 235,
 'famili': 1613,
 'magic': 2715,
 'hors': 2132,
 'fairytal': 1601,
 'music': 3001,
 'selfish': 3950,
 'duringcreditssting': 1384,
 'toni': 4541,
 'stark': 4234,
 'tri': 4597,
 'program': 3488,
 'thing': 4490,
 'awri': 375,
 'hero': 2057,
 'ultim': 4649,
 'test': 4472,
 'fate': 1639,
 'hang': 1992,
 'aveng': 363,
 'stop': 4268,
 'plans': 3357,
 'soon': 4151,
 'unexpect': 4673,
 'way': 4864,
 'global': 1888,
 'adventure': 117,
 'basedoncomicbook': 419,
 'vision': 4801,
 'marvelcinematicunivers': 2779,
 'harri': 2011,
 'begin': 461,
 'sixth': 4075,
 'discov': 1272,
 'old': 3156,
 'book': 559,
 'mark': 2760,
 'properti': 3498,
 'half': 1981,
 'blood': 534,
 'prince': 3463,
 'learn': 2557,
 'lord': 2651,
 'witch': 4922,
 'broom': 621,
 'wizardri': 4925,
 'teenagecrush': 4438,
 'werewolf': 4882,
 'fear': 1647,
 'god': 1892,
 'lik': 2601,
 'left': 2561,
 'city': 837,
 'modern': 2935,
 'day': 1141,
 'wrestl': 4959,
 'sort': 4158,
 'realli': 3603,
 'superman': 4352,
 'threat': 4499,
 'quickli': 3544,
 'mankind': 2743,
 'greater': 1932,
 'danger': 1118,
 'known': 2500,
 'zacksnyd': 4989,
 'return': 3714,
 'allow': 180,
 'luthor': 2698,
 'walk': 4827,
 'free': 1788,
 'wa': 4818,
 'abandon': 61,
 'plot': 3369,
 'million': 2890,
 'kill': 2477,
 'chang': 761,
 'face': 1590,
 'forever': 1749,
 'rid': 3734,
 'steel': 4245,
 'savingtheworld': 3875,
 'bryansing': 631,
 'continu': 988,
 'jame': 2356,
 'casino': 722,
 'betray': 485,
 'woman': 4928,
 '007': 1,
 'fight': 1676,
 'urg': 4724,
 'make': 2724,
 'latest': 2540,
 'pursu': 3531,
 'determin': 1226,
 'interrog': 2298,
 'mr': 2987,
 'white': 4894,
 'organ': 3186,
 'blackmail': 521,
 'far': 1628,
 'complex': 935,
 'anyon': 260,
 'imagined': 2209,
 'undercov': 4660,
 'marcforst': 2751,
 'jack': 2346,
 'work': 4941,
 'debt': 1159,
 'jones': 2419,
 'attempt': 341,
 'avoid': 366,
 'etern': 1520,
 'fortunetel': 1759,
 'monster': 2944,
 'daughter': 1131,
 'texa': 4474,
 'ranger': 3580,
 'chase': 780,
 'outlaw': 3201,
 'led': 2559,
 'ambush': 198,
 'survivor': 4379,
 'american': 200,
 'indian': 2239,
 'nurs': 3127,
 'health': 2034,
 'don': 1320,
 'mask': 2783,
 'ride': 3737,
 'silver': 4048,
 'team': 4430,
 'bring': 607,
 'unscrupul': 4703,
 'justice': 2445,
 'western': 4887,
 'partner': 3258,
 'lawyer': 2548,
 'train': 4577,
 'young': 4981,
 'boy': 575,
 'extraordinari': 1581,
 'power': 3421,
 'thi': 4487,
 'journey': 2427,
 'came': 674,
 'sent': 3960,
 'emerg': 1451,
 'save': 3874,
 'symbol': 4400,
 'hope': 2124,
 'superhuman': 4350,
 'alieninvas': 170,
 'reboot': 3611,
 'incred': 2233,
 'lion': 2612,
 'luci': 2690,
 'susan': 4381,
 'narnia': 3025,
 'aid': 145,
 'princ': 3462,
 'threaten': 4500,
 'evil': 1540,
 'king': 2486,
 'help': 2054,
 'color': 901,
 'cast': 723,
 'characters': 772,
 'clan': 843,
 'embark': 1447,
 'quest': 3541,
 'ensur': 1489,
 'right': 3743,
 'heir': 2047,
 'fictionalplac': 1672,
 'brothersisterrelationship': 626,
 'matteroflifeanddeath': 2801,
 'faith': 1602,
 'uncl': 4654,
 'fantasyworld': 1627,
 'enemi': 1470,
 'safeti': 3844,
 'security': 3940,
 'nick': 3086,
 'director': 1261,
 'intern': 2293,
 'agenc': 136,
 'need': 3051,
 'pull': 3523,
 'disaster': 1270,
 'span': 4181,
 'globe': 1889,
 'dare': 1124,
 'recruit': 3625,
 'effort': 1419,
 'begins': 462,
 'newyork': 3082,
 'shield': 4017,
 'cross': 1071,
 'path': 3267,
 'sure': 4365,
 'ruthless': 3835,
 'artist': 313,
 'use': 4727,
 'fabl': 1588,
 'fountain': 1765,
 'youth': 4987,
 'aboard': 65,
 'queen': 3537,
 'revenge': 3721,
 'formid': 1754,
 'doesn': 1311,
 'know': 2498,
 'sea': 3913,
 'mutini': 3010,
 'sword': 4396,
 'sail': 3848,
 'duke': 1378,
 'mermaid': 2851,
 'agent': 139,
 'smith': 4107,
 'tommi': 4538,
 'lee': 2560,
 'time': 4518,
 'seen': 3946,
 '15': 8,
 'men': 2840,
 'black': 519,
 'aliens': 173,
 'stake': 4223,
 'travel': 4589,
 'univers': 4689,
 'told': 4536,
 'themselv': 4484,
 'josh': 2424,
 'agency': 137,
 'humankind': 2161,
 'comedi': 909,
 'timetravel': 4522,
 'timemachin': 4520,
 'barrysonnenfeld': 415,
 'immedi': 2211,
 'event': 1530,
 'desol': 1213,
 'bilbo': 501,
 'dwarv': 1388,
 'defend': 1175,
 'mountain': 2977,
 'treasur': 4591,
 'claim': 841,
 'ruin': 3819,
 'elv': 1445,
 'meanwhil': 2820,
 'armi': 298,
 'orc': 3181,
 'march': 2752,
 'fuel': 1808,
 'rise': 3750,
 'middle': 2874,
 'fall': 1605,
 'corrupt': 1010,
 'hobbit': 2095,
 'dragon': 1338,
 'unlikelyfriendship': 4696,
 'swordandsorceri': 4397,
 'peterjackson': 3309,
 'outcast': 3199,
 'high': 2066,
 'parent': 3243,
 'leav': 2558,
 'rais': 3572,
 'ben': 472,
 'aunt': 353,
 'like': 2602,
 'teenagers': 4443,
 'figur': 1678,
 'got': 1906,
 'person': 3303,
 'today': 4530,
 'belong': 470,
 'father': 1640,
 'understand': 4666,
 'parents': 3244,
 'disappear': 1266,
 'lead': 2553,
 'lab': 2512,
 'dr': 1335,
 'collis': 896,
 'cours': 1029,
 'choic': 806,
 'destini': 1218,
 'lossoffath': 2659,
 'socialoutcast': 4124,
 'robin': 3771,
 'happen': 1997,
 'die': 1245,
 'robert': 3766,
 'promis': 3493,
 'identity': 2188,
 'widow': 4898,
 'draw': 1342,
 'town': 4560,
 'sheriff': 4014,
 'archer': 288,
 'middleag': 2875,
 'mediev': 2828,
 'ridleyscott': 3740,
 'success': 4325,
 'mountains': 2978,
 'gain': 1824,
 'ring': 3746,
 'gold': 1894,
 'wizard': 4924,
 'shock': 4022,
 'orphan': 3191,
 'trade': 4567,
 'carefre': 707,
 'exist': 1556,
 'roam': 3759,
 'hall': 1983,
 'jordan': 2422,
 'colleg': 892,
 'otherworldli': 3196,
 'north': 3107,
 'unawar': 4652,
 'destiny': 1219,
 'england': 1477,
 'experi': 1567,
 'basedonyoungadultnovel': 428,
 'chrisweitz': 823,
 'york': 4979,
 'ambiti': 196,
 'movi': 2982,
 'produc': 3481,
 'hire': 2084,
 'crew': 1058,
 'skull': 4084,
 'island': 2334,
 'kong': 2501,
 'giant': 1874,
 'ape': 265,
 'smitten': 4108,
 'lady': 2521,
 'screenplay': 3906,
 'filmmak': 1683,
 'filmproduc': 1684,
 'dinosaur': 1257,
 'rose': 3807,
 'tell': 4452,
 'stori': 4271,
 'lizzi': 2627,
 'bobbi': 548,
 'april': 281,
 'titan': 4528,
 'board': 544,
 'depart': 1195,
 'upper': 4716,
 'class': 846,
 'passeng': 3263,
 'mother': 2967,
 'ruth': 3834,
 'fiancé': 1670,
 'drifter': 1351,
 'best': 480,
 'friend': 1797,
 'win': 4911,
 'game': 1830,
 'explain': 1572,
 'voyag': 4816,
 '20': 42,
 'panic': 3233,
 'disast': 1269,
 'classdiffer': 847,
 'starcrossedlov': 4231,
 '1910': 17,
 'age': 134,
 'collect': 890,
 'govern': 1911,
 'pass': 3262,
 'act': 86,
 'design': 1210,
 'polar': 3378,
 'opinion': 3175,
 'caus': 734,
 'faction': 1594,
 'iron': 2330,
 'america': 199,
 'civilwar': 840,
 'beam': 439,
 'radio': 3560,
 'signal': 4044,
 'form': 1753,
 'sever': 3985,
 'craft': 1042,
 'water': 4862,
 'hawaii': 2028,
 'lieuten': 2589,
 'alex': 164,
 'hopper': 2126,
 'weapon': 4869,
 'offic': 3149,
 'assign': 325,
 'paul': 3274,
 'naval': 3036,
 'engag': 1475,
 'unimagin': 4684,
 'strength': 4287,
 'invaders': 2310,
 'live': 2622,
 'potenti': 3416,
 'brother': 623,
 'admir': 103,
 'shane': 4001,
 'expect': 1562,
 'navi': 3037,
 'hongkong': 2118,
 'soccer': 4121,
 'scientist': 3897,
 'park': 3249,
 'featur': 1650,
 'fulli': 1811,
 'theme': 4483,
 'origin': 3189,
 'dna': 1302,
 'tyrannosaurusrex': 4646,
 'suspens': 4383,
 'amusementpark': 211,
 'animalattack': 236,
 'animalhorror': 237,
 'grave': 1928,
 'wrong': 4966,
 'attack': 339,
 'reloc': 3661,
 'author': 357,
 'posit': 3410,
 'challeng': 755,
 'intellig': 2286,
 'secur': 3939,
 'compromis': 939,
 'insid': 2270,
 'alli': 178,
 'trust': 4618,
 'shadow': 3995,
 'onli': 3167,
 'field': 1673,
 'eve': 1528,
 'lethal': 2579,
 'hidden': 2063,
 'motiv': 2972,
 'sociopath': 4127,
 'killer': 2479,
 'major': 2722,
 'ident': 2187,
 'crisis': 1067,
 'burn': 653,
 'decid': 1166,
 'suffer': 4332,
 'wake': 4826,
 'doc': 1303,
 'feel': 1654,
 'mari': 2755,
 'jane': 2364,
 'girl': 1879,
 'sinc': 4057,
 'childhood': 793,
 'doctor': 1305,
 'supervillain': 4358,
 'apart': 262,
 'start': 4236,
 'odyssey': 3147,
 'rebuild': 3612,
 'waronterror': 4849,
 'tennesse': 4455,
 'malibu': 2731,
 'alice': 168,
 'individu': 2242,
 '19': 16,
 'english': 1478,
 'party': 3261,
 'crowd': 1073,
 'consid': 972,
 'marriag': 2763,
 'hole': 2100,
 'garden': 1840,
 'spot': 4208,
 'unusu': 4710,
 'rabbit': 3548,
 'arriv': 306,
 'strang': 4278,
 'surreal': 4373,
 'place': 3351,
 'nightmar': 3093,
 'child': 790,
 'talk': 4413,
 'animals': 238,
 'alic': 167,
 'reason': 3606,
 'conquer': 965,
 'horrif': 2129,
 'restor': 3704,
 'throne': 4503,
 'timburton': 4517,
 'cure': 1092,
 'treat': 4593,
 'line': 2609,
 'drawn': 1343,
 'band': 396,
 'mutant': 3007,
 'beast': 442,
 'brettratn': 596,
 'relationship': 3649,
 'mike': 2883,
 'dure': 1383,
 'friends': 1799,
 'bestfriend': 481,
 'scari': 3884,
 'sam': 3855,
 'normal': 3105,
 'mind': 2893,
 'target': 4420,
 'drag': 1337,
 'egypt': 1422,
 'sun': 4344,
 'chao': 766,
 'artifact': 310,
 'transform': 4581,
 'tank': 4417,
 'robot': 3773,
 'michaelbay': 2866,
 'pick': 3331,
 'vanish': 4744,
 'group': 1948,
 'businessman': 657,
 'push': 3533,
 'boundari': 568,
 'technolog': 4433,
 'control': 991,
 'ancient': 217,
 'menac': 2841,
 'giantrobot': 1875,
 'oscar': 3194,
 'small': 4102,
 'tim': 4516,
 'circu': 832,
 'whisk': 4893,
 'kansa': 2448,
 'land': 2525,
 'oz': 3212,
 'inhabit': 2257,
 'great': 1929,
 'clutch': 871,
 'illus': 2203,
 'lost': 2667,
 'bad': 385,
 'guy': 1971,
 'spend': 4193,
 'loves': 2682,
 'school': 3890,
 'graduat': 1918,
 'stay': 4242,
 'clue': 869,
 'obsess': 3132,
 'electr': 1429,
 'tech': 4432,
 'son': 4146,
 'kevin': 2465,
 'investig': 2315,
 'dictat': 1242,
 'real': 3598,
 'artificialintellig': 312,
 'dystopia': 1395,
 'comput': 941,
 'decept': 1165,
 'duel': 1377,
 'motorcycl': 2975,
 'star': 4230,
 'race': 3550,
 'car': 700,
 'lightn': 2600,
 'pal': 3225,
 'compet': 931,
 'grand': 1920,
 'road': 3756,
 'championship': 758,
 'rocki': 3779,
 'intrigu': 2307,
 'carrac': 715,
 'anthropomorph': 254,
 'centuries': 747,
 'warrior': 4851,
 'green': 1938,
 'corp': 1006,
 'intergalact': 2292,
 'wear': 4871,
 'grant': 1925,
 'destroy': 1220,
 'balanc': 390,
 'universe': 4690,
 'lie': 2588,
 'hand': 1987,
 'martincampbel': 2777,
 'buzz': 665,
 'andy': 225,
 'toy': 4562,
 'haven': 2026,
 'play': 3361,
 'andi': 221,
 'college': 893,
 'accident': 76,
 'nefari': 3052,
 'care': 705,
 'center': 743,
 'togeth': 4533,
 'home': 2105,
 'toycomestolif': 4563,
 'grown': 1952,
 'post': 3413,
 'apocalypt': 269,
 'connor': 964,
 'resist': 3691,
 'increasingli': 2232,
 'domin': 1318,
 'marcu': 2753,
 'wright': 4962,
 'confus': 958,
 'foe': 1729,
 'propheci': 3499,
 'sanfrancisco': 3864,
 'cyborg': 1107,
 'killerrobot': 2480,
 'gasstat': 1846,
 'firearm': 1695,
 'losangel': 2652,
 'mcg': 2815,
 'shaw': 4009,
 'seek': 3944,
 'toretto': 4545,
 'speed': 4190,
 'jameswan': 2361,
 'unit': 4687,
 'nation': 3030,
 'lane': 2527,
 'content': 985,
 'suddenly': 4330,
 'plagu': 3352,
 'infect': 2251,
 'turn': 4626,
 'popul': 3399,
 'rampag': 3576,
 'zombies': 4997,
 'bare': 406,
 'chaos': 767,
 'persuad': 3304,
 'disease': 1275,
 'peril': 3296,
 'trek': 4596,
 'brave': 584,
 'odd': 3144,
 'answer': 249,
 'befor': 457,
 'civil': 838,
 'falls': 1608,
 'horror': 2131,
 'apocalyps': 267,
 'zombi': 4995,
 'zombieapocalyps': 4996,
 'speci': 4185,
 'period': 3297,
 'join': 2415,
 'younger': 4984,
 'future': 1818,
 '1970': 30,
 'storm': 4273,
 'enterpris': 1492,
 'unstopp': 4707,
 'fleet': 1713,
 'everyth': 1538,
 'stand': 4227,
 'state': 4238,
 'score': 3898,
 'kirk': 2489,
 'manhunt': 2739,
 'captur': 698,
 'mass': 2785,
 'destruction': 1223,
 'friendship': 1800,
 'sacrific': 3839,
 'spacecraft': 4174,
 'spaceopera': 4177,
 'unwittingli': 4714,
 'open': 3171,
 'fearsom': 1649,
 'unleash': 4693,
 'strive': 4296,
 'reclaim': 3616,
 'onc': 3165,
 'people': 3292,
 'thought': 4497,
 'legend': 2566,
 'chanc': 759,
 'adapt': 99,
 'scott': 3900,
 'novel': 3116,
 'midwestern': 2881,
 'lure': 2695,
 'lavish': 2544,
 'neighbor': 3055,
 'jay': 2369,
 'crack': 1041,
 'rich': 3728,
 'existence': 1557,
 'obsession': 3133,
 'madness': 2708,
 'tragedi': 4572,
 'await': 367,
 'infidel': 2252,
 'rogu': 3783,
 'capabl': 692,
 'releas': 3652,
 'gift': 1876,
 'rule': 3820,
 'basedonvideogam': 427,
 'mikenewel': 2884,
 'legion': 2569,
 'monstrou': 2946,
 'creatures': 1055,
 'kaiju': 2447,
 'began': 460,
 'consum': 980,
 'humanity': 2160,
 'resourc': 3695,
 'end': 1466,
 'combat': 904,
 'special': 4186,
 'type': 4643,
 'massiv': 2787,
 'simultan': 4055,
 'pilot': 3342,
 'prove': 3509,
 'nearli': 3047,
 'relentless': 3654,
 'verg': 4758,
 'defeat': 1174,
 'heroes': 2058,
 'charli': 776,
 'drive': 1354,
 'legendari': 2567,
 'mount': 2976,
 'apocalypse': 268,
 'step': 4248,
 'adulthood': 112,
 'remain': 3664,
 'reluct': 3662,
 'prime': 3461,
 'film': 1681,
 'usa': 4725,
 'suggest': 4334,
 'role': 3785,
 'secrets': 3935,
 'bodyguard': 552,
 'sabotag': 3837,
 'commando': 920,
 'cold': 882,
 'soviet': 4171,
 'wield': 4899,
 'search': 3916,
 'crystal': 1082,
 'supernatur': 4354,
 'relat': 3648,
 'mystic': 3014,
 'indi': 2237,
 'peru': 3305,
 'colleagu': 888,
 'professor': 3485,
 'knowledg': 2499,
 'riddl': 3736,
 'whip': 4892,
 'machinegun': 2703,
 'treasurehunt': 4592,
 ...}

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
similarity = cosine_similarity(vectors)

In [57]:
similarity[0]

array([1.        , 0.08980265, 0.08980265, ..., 0.04622502, 0.        ,
       0.        ])

In [58]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

119

In [63]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(1216, 0.2849014411490948),
 (539, 0.26940795304016235),
 (3730, 0.2676516895156553),
 (507, 0.26490647141300877),
 (582, 0.25182770057259657)]

In [64]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [67]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
10th & Wolf
Synecdoche, New York

and now you can use this as a architecture for any application